### ISSUE TITLE
Error when running somax2_server

### ISSUE THREAD

**Issue by sirnotto** [DYCI2/Somax2#1]
I am really looking forward to trying Somax2. However, I am having an issue when trying to start the server. I get the error message:

> [ERROR]: asyncio.run() cannot be called from a running event loop
Traceback (most recent call last):
File "ipython-input-3-5af66a27494c", line 435, in <module>
    asyncio.run(gather())
File "/anaconda3/lib/python3.7/asyncio/runners.py", line 34, in run
    "asyncio.run() cannot be called from a running event loop")
RuntimeError: asyncio.run() cannot be called from a running event loop

It is not immediately clear to me how I can fix this. Is this a familiar issue?

**Comment by sirnotto** [comment]
Ah... never mind! I was trying to run the file from an IDE instead of in the terminal. It's working fine, no worries.
